--- #YAML:1.0
name: WebService-StreetMapLink
version: 0.02
author: David Rolsky <autarch@urth.org>
abstract: An API for generating links to online map services
license: perl
requires:
  Geography::States: 0
  Params::Validate: 0
  Test::More: 0
provides:
  WebService::StreetMapLink:
    file: lib/WebService/StreetMapLink.pm
    version: 0.02
  WebService::StreetMapLink::MapQuest:
    file: lib/WebService/StreetMapLink/MapQuest.pm
  WebService::StreetMapLink::Multimap:
    file: lib/WebService/StreetMapLink/Multimap.pm
  WebService::StreetMapLink::Streetdirectory:
    file: lib/WebService/StreetMapLink/Streetdirectory.pm
generated_by: Module::Build version 0.25
