---
name: WebService-StreetMapLink
version: 0.08
author:
  - David Rolsky <autarch@urth.org>
abstract: An API for generating links to online map services
license: perl
requires:
  Class::Factory::Util: 0
  Geography::States: 0
  Params::Validate: 0
  Test::More: 0
provides:
  WebService::StreetMapLink:
    file: lib/WebService/StreetMapLink.pm
    version: 0.08
  WebService::StreetMapLink::Catcha:
    file: lib/WebService/StreetMapLink/Catcha.pm
  WebService::StreetMapLink::Google:
    file: lib/WebService/StreetMapLink/Google.pm
  WebService::StreetMapLink::MapQuest:
    file: lib/WebService/StreetMapLink/MapQuest.pm
  WebService::StreetMapLink::Multimap:
    file: lib/WebService/StreetMapLink/Multimap.pm
  WebService::StreetMapLink::Streetdirectory:
    file: lib/WebService/StreetMapLink/Streetdirectory.pm
generated_by: Module::Build version 0.261
